#!/bin/bash

#----------------------------------------------------------------
###             FOR ROOT ADMINISTRATOR EXECUTING              ###
#----------------------------------------------------------------
# Install: [root]
#	vim git python-scipy python-dev python-pip python-nose gcc g++
#	libopenblas-dev openssh-server fail2ban python-opencv samba
#
# Pip install:
#	virtualenv numpy scipy nose python-opencv
#
# General Setting:
#	selected_editor="/usr/bin/vim.basic" > /root/.selected_editor
#
# Setting:
#	sshd-setup
#	fail2ban
#
### Written by Bassy<aaammmyyy27@gmail.com> 2017/04/21 v.3.0

if ! [[ $USER = "root" ]]; then
	echo "-Usage:	sudo bash $0"
	exit 0
fi

# Insatll
echo "Install Package ...."
echo "> sudo apt-get update [need root]"
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install -y vim git python-numpy python-scipy python-dev python-pip python-nose gcc g++ libopenblas-dev openssh-server fail2ban python-opencv samba
echo 

# Pip install
echo "> sudo pip install --upgrade pip virtualenv numpy scipy nose python-opencv"
sudo pip install --upgrade pip
sudo pip install --upgrade virtualenv numpy scipy nose python-opencv
echo 

# `select-editor`
#sudo echo -e "\
## Generated by /usr/bin/select-editor \n\
#SELECTED_EDITOR=\"/usr/bin/vim.basic\"" > /root/.selected_editor

# SSHd setting [root]
read -p "Modify sshd setting [need root]? [y/N] " ans_sshd
if [[ $ans_sshd =~ ^[yY]+$ ]]; then
	read -p "Enter the port number for this server: [22] " pt
	! [[ $pt =~ ^[0-9]{1,5}$ ]] && pt=22
	test -e setup/sshd-setup.sh && bash setup/sshd-setup.sh $pt
	echo 
	echo "Set sshd completely."
fi
echo 

# SAMBA setting [root]
#

# Fail2ban setting [root]
# (from: https://www.linode.com/docs/security/using-fail2ban-for-security)
read -p "Setup Fail2ban [nead root]? [Y/n] " ans_f2b
if [[ $ans_f2b =~ ^[yY]*$ ]]; then
	sudo apt-get install -y fail2ban
	sudo ufw allow ssh
	sudo ufw enable
	sudo cp /etc/fail2ban/fail2ban.conf /etc/fail2ban/fail2ban.local
	sudo cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
	read -p "Enter your email to receive fail2ban message: " email
	#sed -i "s/\(ignoreip = .*$\)/\1 140\.114\.75\.33/g" /etc/fail2ban/jail.local
	sudo sed -i "s/\(bantime  = \)600$/\136000/g" /etc/fail2ban/jail.local
	sudo sed -i "s/\(destemail \+= \).*$/\1$email/g" /etc/fail2ban/jail.local
	sudo sed -i "s/\(sender \+= \).*$/\1sendmail -t $email/g" /etc/fail2ban/jail.local
	echo 
	echo "Install fail2ban completely."
fi
echo 

# Done
echo "Done!"

